baseurl: ""
url: "http://sblask.github.io"
author: Sebastian Blask

markdown: kramdown

author_image: http://www.gravatar.com/avatar/b96587b41ce6e2c354db9e04ecfc32e1?s=200
title: Sebastian Blask's Tech Blog
description: >
  My name is Sebastian Blask and I am a developer currently living in
  Stockholm, Sweden. This is the place where I write about technical stuff. I
  hope it helps others or makes them learn something new.
